Light/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('notes.urls')),
]

notes/urls.py
__author__ = 'Jeezy'

from django.conf.urls import include, url
from notes.forms import MyLoginForm

urlpatterns = [
    url(r"^$", 'notes.views.home', name='home'),
    url(r'^auth/login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'notes/auth/login.html',
            'authentication_form': MyLoginForm,
            'extra_context':
            {
                'title': 'Вход пользователя',
            }
        },
        name='login'),
    url(r'^auth/logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r"^auth/register/$", 'notes.views.register', name='register'),
    url(r"^auth/register/success/$", 'notes.views.register_success', name='register_success'),
    url(r"^personal/$", 'notes.views.personal_show', name='personal_show'),
    url(r"^personal/categories/$", 'notes.views.personal_categories', name='personal_categories'),
    url(r"^personal/categories/(?P<category_id>[0-9]+)/delete/$", 'notes.views.personal_categories_delete',
        name='personal_categories_delete'),
    url(r"^personal/edit/$", 'notes.views.personal_edit', name='personal_edit'),
    url(r"^personal/edit/avatar/$", 'notes.views.personal_edit_avatar', name='personal_edit_avatar'),
    url(r"^users/$", 'notes.views.users', name='users'),
    url(r"^users/(?P<username>\w+)/$", 'notes.views.user_show', name='user_show'),
    url(r"^users/(?P<username>\w+)/notes/$", 'notes.views.user_notes', name='user_notes'),
    url(r"^users/(?P<username>\w+)/notes/add/$", 'notes.views.user_notes_modify', name='user_notes_add'),
    url(r"^users/(?P<username>\w+)/notes/(?P<note_id>[0-9]+)/$", 'notes.views.user_notes_show', name='user_notes_show'),
    url(r"^users/(?P<username>\w+)/notes/(?P<note_id>[0-9]+)/edit/$",
        'notes.views.user_notes_modify',
        name='user_notes_edit'),
    url(r"^users/(?P<username>\w+)/notes/(?P<note_id>[0-9]+)/delete/$",
        'notes.views.user_notes_delete',
        name='user_notes_delete'),
    url(r"^users/(?P<username>\w+)/notes/(?P<note_id>[0-9]+)/labels/add/$",
        'notes.views.user_notes_labels_add',
        name='user_notes_labels_add'),
    url(r"^users/(?P<username>\w+)/notes/(?P<note_id>[0-9]+)/labels/(?P<label_id>[0-9]+)/delete/$",
        'notes.views.user_notes_labels_delete',
        name='user_notes_labels_delete'),
]

notes/models.py
import datetime
import os
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.core.files.storage import FileSystemStorage


# Класс для перезаписи существующих файлов
class OverwriteStorage(FileSystemStorage):

    def get_available_name(self, name):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


# Расширенная модель пользователя
class MyUser(AbstractUser):
    date_of_birth = models.DateField(default=datetime.datetime.now)
    phone = models.CharField(_('Телефон'), max_length=40, default='', blank=False, null=False)
    avatar = models.ImageField(upload_to='notes/avatars/', blank=True, storage=OverwriteStorage())
    is_private = models.BooleanField(_('Приватные заметки'), default=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    class Meta(object):
        unique_together = ('email',)


# Модель цыета заметок
class ColorOfNote(models.Model):
    name = models.CharField(_("Цвет заметки"), max_length=30, blank=True)
    color = models.CharField(_("Цвет в hex"), max_length=30, blank=True)

    def __str__(self):
        return self.name


# Категории
class Category(models.Model):
    name = models.CharField(max_length=50)
    parent_category = models.ForeignKey("self", blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.name


# Стандартные ярлыки
class LabelDefault(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Заметки
class Note(models.Model):
    title = models.CharField(_('Название'), max_length=50, blank=False)
    message = models.CharField(_("Текст"), max_length=1000, blank=False)
    file = models.FileField(upload_to='notes/files/', blank=True)
    color = models.ForeignKey(ColorOfNote, blank=True, default='1', null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    categories = models.ManyToManyField(Category, blank=True)
    labels = models.ManyToManyField(LabelDefault, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.message


# Ярлыки пользователя
class LabelCustom(models.Model):
    file = models.ImageField(upload_to='notes/labels/custom/', blank=True)
    note = models.ForeignKey(Note, blank=True, null=True)

    def __str__(self):
        return str(self.file)

notes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from .models import MyUser, Note, Category, LabelCustom
from .forms import MyRegForm, ModifyNoteForm, EditProfileForm, AddLabelForm, EditAvatarForm


def home(request):
    return render(request, 'notes/home.html')


def register(request):
    if request.method == 'POST':
        form = MyRegForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/auth/register/success')
    else:
        form = MyRegForm()

    return render(request, 'notes/auth/register.html', {'form': form})


def register_success(request):
    return render(request, 'notes/auth/register_success.html')


# Список пользователей
def users(request):
    users_list = MyUser.objects.order_by('id')
    paginator = Paginator(users_list, 2)
    page = request.GET.get('page')
    try:
        users_list = paginator.page(page)
    except PageNotAnInteger:
        users_list = paginator.page(1)
    except EmptyPage:
        users_list = paginator.page(paginator.num_pages)
    return render(request, 'notes/users/index.html', {'users_list': users_list})


# Вывод информации о пользователе
@login_required(login_url='/auth/login/')
def user_show(request, username):
    user = get_object_or_404(MyUser, username=username)
    return render(request, 'notes/users/show.html', {'user': user})


# Вывод списка заметок выбранного пользователя
@login_required(login_url='/auth/login/')
def user_notes(request, username):
    user_owner = get_object_or_404(MyUser, username=username)
    """
    Список заметок будет показан если пользователь является автором заметки или
    если он открыл их для общего доступа
    """
    if user_owner.username == request.user.username or not user_owner.is_private:
        pass
    else:
        raise Exception('Этот пользователь закрыл свои заметки.')

    # Проверяем если ли у выбранного пользователя созданные заметки
    try:
        notes = user_owner.note_set.order_by('-created_at')
    except AttributeError:
        notes = None
    else:
        paginator = Paginator(notes, 6)
        page = request.GET.get('page')
        try:
            notes = paginator.page(page)
        except PageNotAnInteger:
            notes = paginator.page(1)
        except EmptyPage:
            notes = paginator.page(paginator.num_pages)
    return render(request, 'notes/notes/index.html', {'notes': notes, 'user_owner': user_owner})


# Вывод детальной информации о заметке
@login_required(login_url='/auth/login/')
def user_notes_show(request, username, note_id):
    user_owner = get_object_or_404(MyUser, username=username)
    note = get_object_or_404(Note, id=note_id)
    # Заметка будет показана если пользователь является автором заметки или если он открыл их для общего доступа
    if user_owner.username == request.user.username or not user_owner.is_private:
        pass
    else:
        raise Exception('Этот пользователь закрыл свои заметки.')
    return render(request, 'notes/notes/show.html', {'note': note})


# Создание или удаление заметки
@login_required(login_url='/auth/login/')
def user_notes_modify(request, username, note_id=None):
    """
    Если в url была id заметки проверяем является ли пользователь автором заметки
    Также заносим в переменную обьект заметки для ее редактирования
    """
    if note_id is not None:
        try:
            note = request.user.note_set.get(id=note_id)
        except:
            raise Exception('Вы пытаетесь редактировать заметку другому пользователю?')
        foo = 'Редактировать'
    # Создаем форму для редактирвоания или создания заметки.Проверяем владельца
    else:
        user_owner = get_object_or_404(MyUser, username=username)
        if not user_owner.username == request.user.username:
            raise Exception('Вы пытаетесь добавить заметку другому пользователю?')
        note = None
        foo = 'Добавить'
    if request.method == 'POST':
        form = ModifyNoteForm(request.user, request.POST, request.FILES, instance=note)
        if form.is_valid():
            first = form.save(commit=False)
            first.user = request.user
            first.save()
            form.save_m2m()
            return HttpResponseRedirect('/users/' + username + '/notes/' + str(first.id) + '/')
        return render(request, 'notes/notes/modify.html', {'form': form, 'note': note})
    else:
        form = ModifyNoteForm(instance=note, user=request.user)

    return render(request, 'notes/notes/modify.html', {'note': note, 'form': form,
                                                       'foo': foo})


# Удаление заметки
@login_required(login_url='/auth/login/')
def user_notes_delete(request, username, note_id):
    if request.method == 'POST':
        user_owner = get_object_or_404(MyUser, username=username)
        if not user_owner.username == request.user.username:
            raise Exception('Вы пытаетесь удалить заметку другому пользователю?')
        note = get_object_or_404(Note, id=note_id)
        note.delete()
    return HttpResponseRedirect('/users/' + username + '/notes')


# Личный кабинет
@login_required(login_url='/auth/login/')
def personal_show(request):
    return render(request, 'notes/personal/index.html')


# Редактирование личной информации пользателя
@login_required(login_url='/auth/login/')
def personal_edit(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Личные данные успешно отредактированы!')
            return HttpResponseRedirect('/personal/')
    else:
        form = EditProfileForm(instance=request.user)
    return render(request, 'notes/personal/edit.html', {'form': form})


# Создание собственных ярлыков
@login_required(login_url='/auth/login/')
def user_notes_labels_add(request, username, note_id):
    user_owner = get_object_or_404(MyUser, username=username)
    if not user_owner.username == request.user.username:
        raise Exception('Доступ запрещен')
    if request.method == 'POST':
        form = AddLabelForm(request.POST, request.FILES)
        if form.is_valid():
            note = request.user.note_set.get(id=note_id)
            first = form.save(commit=False)
            first.note = note
            first.save()
            messages.success(request, 'Ярлык добавлен!')
            return HttpResponseRedirect('/users/' + request.user.username + '/notes/' + note_id + '/')
    else:
        form = AddLabelForm()
    return render(request, 'notes/labels/add.html', {'form': form})


# Удаление собственного ярлыка
@login_required(login_url='/auth/login/')
def user_notes_labels_delete(request, username, note_id, label_id):
    try:
        note = request.user.note_set.get(id=note_id)
    except:
        raise Exception('Вы пытаетесь удалить значок другого пользователя?')
    label = get_object_or_404(LabelCustom, id=label_id)
    label.delete()
    messages.success(request, 'Ярлык удален!')
    return HttpResponseRedirect('/users/' + request.user.username + '/notes/' + note_id + '/')


# Загрузка и редактирование аватарки
@login_required(login_url='/auth/login/')
def personal_edit_avatar(request):
    if request.method == 'POST':
        form = EditAvatarForm(request.POST, request.FILES, instance=request.user)
        # Делаем имя аватарки как логин у пользователя
        request.FILES['avatar'].name = str(request.user.username) + request.FILES['avatar'].name[-4:]
        if form.is_valid():
            form.save()
            messages.success(request, 'Аватар успешно загружен!')
            return HttpResponseRedirect('/personal/')
    else:
        form = EditAvatarForm(instance=request.user)
    return render(request, 'notes/users/avatar.html', {'form': form})


# Создание и удаление категорий пользователя
@login_required(login_url='/auth/login/')
def personal_categories(request):
    if request.method == 'POST':
        # Ошибка если пользователь не указал родительскую категорию
        try:
            request.POST["parent"]
        except:
            raise Exception('Вы не ввели значение для главной категории!')
        # Создаем новый обьект и сохраняем его
        parent = Category(name=request.POST["parent"], user_id=request.user.id)
        parent.save()
        callback = 'Категория добалена!'
        # Перебираем список дочерних категорий,создаем и сохраняем их обьекты
        for value in request.POST.getlist("child"):
            child = Category(name=value, parent_category_id=parent.id, user_id=request.user.id)
            child.save()
            callback = 'Категории добалены!'
        messages.success(request, callback)
        return HttpResponseRedirect('/personal/')
    else:
        parent_note = request.user.category_set.filter(parent_category_id__isnull=True)
    return render(request, 'notes/personal/categories.html', {'parent_note': parent_note})


# Удаление категорий
@login_required(login_url='/auth/login/')
def personal_categories_delete(request, category_id):
    try:
        category = request.user.category_set.get(id=category_id)
    except:
        raise Exception('Вы пытаетесь удалить категорию другому пользователю?')
    category.delete()
    messages.success(request, 'Категория удалена!')
    return HttpResponseRedirect('/personal/categories/')

notes/templates/notes/notes/index.html
{% extends 'notes/layout.html' %}
{% load staticfiles %}
{% block title %}
    Заметки пользователя {{ user_owner }}
{% endblock %}

{% block content %}
    {% if user_owner|slugify == request.user.username|slugify or not user_owner.is_private %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-6 col-md-9 col-sm-9 col-xs-12">
                        <h1>Заметки пользователя {{ user_owner }}</h1>
                    </div>
                    <div class="col-lg-6 col-md-3 col-sm-3 col-xs-12" style="margin-top: 25px;">
                        <a href="{% url 'user_notes_add' request.user.username %}"
                           class="btn btn-warning pull-right">Добавить заметку</a>
                    </div>
                </div>
            </div>
        </div>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Главная</a></li>
            <li class="active">Заметки</li>
        </ol>
        <hr>
        <div class="row">
            {% for note in notes %}
                <a href="{% url 'user_notes_show' user_owner.username note.id %}">
                    <div class="lal col-lg-4 col-ms-4 col-sm-6 col-xs-12"
                         style="margin-bottom: 20px;padding: 0 10px;">

                        <div class="notes text-center animated bounceInDown"
                             style="background-color: {{ note.color.color }};">
                            {# onclick="window.location='{% url 'user_notes_show' user_owner.username note.id %}';" #}
                            <div class="row">
                                <div class="notes_labels col-lg-12 col-md-12 col-sm-12 col-xs-12"
                                     style="height: 48px;overflow: hidden;">
                                    {% for label in note.labels.all %}
                                        <img src="{% static 'notes/labels/default/' %}{{ label }}" alt="Label"
                                             width="48" height="48">
                                    {% empty %}
                                        <img src="{% static 'notes/labels/default/calendar.png' %}" alt="Label"
                                             width="48" height="48">
                                    {% endfor %}
                                    {% for label in note.labelcustom_set.all %}
                                        <img src="{% static '' %}{{ label }}" alt="Label" width="48" height="48">
                                    {% endfor %}
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <h4 style="word-break: break-all;">{{ note.title|truncatechars:35 }}</h4>
                                </div>
                            </div>
                            <pre>{{ note.message|truncatechars:180 }}</pre>
                        </div>
                    </div>
                </a>
            {% empty %}
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                {% if user_owner|slugify != request.user.username|slugify %}
                    Этот пользователь еще не создавал заметок
                {% else %}
                    <h3>
                        Вы еще не создавали заметок!
                        <a href="{% url 'user_notes_add' request.user.username %}">Создайте заметку прямо
                            сейчас.</a>
                    </h3>
                {% endif %}
                </div>
            {% endfor %}
        </div>
        <nav>
            <ul class="pager">
                {% if notes.has_previous %}
                    <li><a href="?page={{ notes.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% if notes.has_next %}
                    <li><a href="?page={{ notes.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <h1 class="text-center">Этот пользователь закрыл свои заметки.</h1>
    {% endif %}

{% endblock %}

notes/templates/notes/notes/modify.html
{% extends 'notes/layout.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block title %}
    {{ foo }} заметку
{% endblock %}

{% block content %}

    <h1>{{ foo }} заметку</h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">Главная</a></li>
        <li><a href="{% url 'user_notes' request.user.username %}">Мои заметки</a></li>
        <li class="active">{{ foo }} заметку</li>
    </ol>
    <hr>
    <div class="col-md-8 col-sm-10">
        <form class="form-horizontal"
              name="add_comment_form" role="form" method="POST"
              action="#" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
                <div class="col-md-12">
                    <div class="panel-body">
                        <div class="alert alert-danger">
                            <ul>
                                {{ form.errors }}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% bootstrap_form form layout='horizontal' size='medium' horizontal_label_class='col-md-2' horizontal_field_class='col-md-7' %}
            <div class="form-group">
                <div class="col-md-6 col-md-offset-2 text-center">
                    <input type="submit" class="btn btn-primary" name="submit" value="{{ foo }} заметку">
                </div>
            </div>
        </form>
    </div>

{% endblock %}

notes/templates/notes/notes/show.html
{% extends 'notes/layout.html' %}
{% load staticfiles %}
{% block title %}
    {{ note.title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12" style="word-break: break-all;">
            <h1 style="margin-top: 0;">{{ note.title }}</h1>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 text-right">
            {% if request.user.username == note.user.username %}
                <a href="{% url 'user_notes_edit' request.user.username note.id %}" class="btn btn-info"
                   style="margin-top: 10px;">Редактировать</a>
                <form action="{% url 'user_notes_delete' request.user.username note.id %}" method="post"
                      style="margin: 10px 0 0 0;">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit"
                            onclick="return confirm('Вы уверены,что хотите удалить эту заметку?')">Удалить заметку
                    </button>
                </form>
            {% else %}
                <a href="{% url 'user_notes'  request.user.username %}" class="btn btn-info" style="margin-top: 10px;">Посмотреть <br />
                    мои заметки</a>
            {% endif %}
        </div>
        <div class="col-lg-12 col-md--12 col-sm-12 col-xs-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="messenger alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <h3 style="margin: 0;">
                <small>Автор:<a href="{% url 'user_show' note.user.username %}">{{ note.user.username }}</a></small>
            </h3>
            <pre>{{ note.message }}</pre>

            <h3><a href="{% url 'personal_categories' %}">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
                Категории:
                {% for category in note.categories.all %}
                    <small>{{ category }}</small>
                {% empty %}
                    <small>Категории не выбраны.</small>
                {% endfor %}
            </h3>
            <hr/>
            <h3><a href="{% url 'user_notes_labels_add'  request.user.username note.id %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>
                Ярлыки: <br/>
                <small>Нажмите на значок ,чтобы удалить его</small>
                {% for label in note.labels.all %}
                    <img class="labels_in_show" src="{% static 'notes/labels/default/' %}{{ label }}" alt="Label"
                         width="96" height="96">
                {% empty %}
                    <small>Ярлыки не выбраны.</small>
                {% endfor %}

                {% for label in note.labelcustom_set.all %}
                    <a href="{% url 'user_notes_labels_delete'  request.user.username note.id label.id %}"><img
                            class="labels_in_show" src="{% static '' %}{{ label }}" alt="Label" width="96" height="96"></a>
                {% empty %}
                    <small>Добавьте ваши собственные ярлыки.</small>
                {% endfor %}
            </h3>
            <hr/>
            <div class="row">
                <div class="col-md-1 col-sm-2 col-xs-3">
                    <h3>Цвет:</h3>
                </div>
                <div class="notes-show-color-block col-md-2 col-sm-2 col-xs-7"
                     style="background-color: {{ note.color.color }}">
                </div>
            </div>
            <hr/>
            <h3>Файл: <a href="{% static note.file %}">
                <small>{{ note.file|default:"Отсутствует" }}</small>
            </a></h3>
            <hr/>
            <h3>Дата добавления:
                <small>{{ note.created_at }}</small>
            </h3>
        </div>
        <hr>
    </div>

{% endblock %}